author 'simpled-dev'
game 'gta5'
version '1.0.0'
fx_version 'cerulean'
description 'a simple LiveMap without external dependencies for FiveM'
server_script 'server/LiveMap.Server.net.dll'
repository 'https://github.com/all-in-simplicity/simple-livemap'